import DefaultTags from '@zyzle-dev/app/DefaultTags';

export default function Head() {
	return (
		<>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<DefaultTags />
		</>
	);
}
